name: BBC Russian Parser

on:
  workflow_dispatch: # Позволяет запускать скрипт через API (из cron-job.org)

  repository_dispatch:
    types: [ trigger_pipeline ]

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests

      - name: Run BBC Parser Script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python bbc_parser.py

      - name: Commit and push state changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bbc_state.json
          git commit -m "Update BBC parser state [skip ci]" || echo "No changes to state file"
          git push
